[[env]]
_.source = '.envrc'

[tools]
task = 'latest'
jq = 'latest'
terraform = 'latest'
powershell-core = 'latest'
uv = 'latest'
aws-cli = "latest"
atmos = "latest"
python = "3.13"
gomplate = "latest"
